language: r
cache: packages
sudo: false

r_github_packages:
  - jimhester/covr

env:
  global:
  - R_LIBS="https://cran.rstudio.com"

notifications:
  email:
    on_success: change
    on_failure: change
  slack:
    secure: FdOnMLs8w+Ycy/WwbJIYg4m+Fw1AH5RsOldta25IcVvAk429hYGZ6dYllaSBQr6Oux+Xd4aA1Kix2kIjEmH9h3D1WYtrKKBobfu5Uwpl9GYui4G33tC8gip+oqhmOUbPCnNfjoNUdjbqXEo8PQx4jxv7ftngSc3SUvtq4V99DDaqRT3SikfGaXy5GruCWTLNEREYDPtebLWyVliv2brD1c+fpVQ4KdprsVO6feNbMbj6vNj6w3Fyf8CW+HvxsL/7CmxZFbdXz5ivrH5I26AoLWR2JsUaDKUrbkK/ZOMZd6U/yXyYOq1SB/XpvaOrRq230NnTCwQfceGcDx1EGH5Bela+gMLBHp02HcthJDbwRp8O4B1Db+gPdh/wObKlE3Pu/N9zp8tD8x0m5ayrphaRv44hRZzt40Lfvwpw3O3AU3LUxSex3mbKXSpvh5iiUtj4g4sUHwEsQgP0wDY7OQj7XtBdoqpvzmKkHsfcZ+fU96hzcutDezqFnBUWELZNA+ypyzqeYzO+sY3a//seEsr/cFwt1H0E71ZDkoZggwerVHkyaubti7wq6JTVhVjTKoEOy2JfF0StGFsYH4f10wwN3g09X7JhRaWIsltqsiO4LRmaZzk3EoLLcRpwE6Tug6oZQQGSUjMU85cPcRPAznYFMbPBric87MHTNo2Fr5R3AAg=
